### ISSUE TITLE
How to port the existing knative services into the serving progressive rollout

### ISSUE THREAD

**Issue by houshengbo** [knative-extensions/serving-progressive-rollout#67]
Launch some knative services with the serving, and change the images into use the ones in serving progressive rollout.
Verify if the existing knative services are imported to the RO.

If not, may need to fix it.

**Comment by houshengbo** [comment]
Resolved this issue:
```panic: runtime error: index out of range [-1]

goroutine 618 [running]:
knative.dev/serving-progressive-rollout/pkg/reconciler/service.refreshStage(0xc0012fd328?, {0xc0002aa620, 0x1, 0x418408?}, 0x0, 0xffffffffffffffff, 0x1, 0x14, 0x5, 0x64)
	knative.dev/serving-progressive-rollout/pkg/reconciler/service/service.go:634 +0x826
knative.dev/serving-progressive-rollout/pkg/reconciler/service.calculateStageTargetRevisions(0x1?, {0xc0002aa620?, 0x1, 0x1}, {0xc0002aa4d0, 0x50?, 0x1fffc00?}, 0x1, 0x14, 0x5, ...)
	knative.dev/serving-progressive-rollout/pkg/reconciler/service/service.go:709 +0x892
knative.dev/serving-progressive-rollout/pkg/reconciler/service.updateStageTargetRevisions(0xc001776000, 0xc0013636e0, {0x243d0b0?, 0xc0012d9be0?})
	knative.dev/serving-progressive-rollout/pkg/reconciler/service/service.go:484 +0x3b4
knative.dev/serving-progressive-rollout/pkg/reconciler/service.updateRolloutOrchestrator(0xc001776000, {0x243d0b0?, 0xc0012d9be0?}, 0xc0002aa4d0?)
	knative.dev/serving-progressive-rollout/pkg/reconciler/service/service.go:364 +0x1b5
knative.dev/serving-progressive-rollout/pkg/reconciler/service.(*Reconciler).createRolloutOrchestrator(0xc000261550, {0x24561f0, 0xc00109b650}, 0xc000263400, 0x243a6e0?, 0xc000263848?)
	knative.dev/serving-progressive-rollout/pkg/reconciler/service/service.go:306 +0xcd
knative.dev/serving-progressive-rollout/pkg/reconciler/service.(*Reconciler).rolloutOrchestrator(0xc000261550, {0x24561f0, 0xc00109b650}, 0xc000263400, 0xff?)
	knative.dev/serving-progressive-rollout/pkg/reconciler/service/service.go:247 +0x416
knative.dev/serving-progressive-rollout/pkg/reconciler/service.(*Reconciler).ReconcileKind(0xc000261550, {0x2456148, 0xc0012eb530}, 0xc000263400)
	knative.dev/serving-progressive-rollout/pkg/reconciler/service/service.go:150 +0x552
knative.dev/serving/pkg/client/injection/reconciler/serving/v1/service.(*reconcilerImpl).Reconcile(0xc000872640, {0x2456148, 0xc0012eb3b0}, {0xc001363680, 0x14})
	knative.dev/serving@v0.40.1-0.20240205183227-1760f08360f2/pkg/client/injection/reconciler/serving/v1/service/reconciler.go:240 +0x570
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc0008c5200)
	knative.dev/pkg@v0.0.0-20240205092023-4104e4237f6a/controller/controller.go:542 +0x4ad
knative.dev/pkg/controller.(*Impl).RunContext.func3()
	knative.dev/pkg@v0.0.0-20240205092023-4104e4237f6a/controller/controller.go:491 +0x59
created by knative.dev/pkg/controller.(*Impl).RunContext in goroutine 590
	knative.dev/pkg@v0.0.0-20240205092023-4104e4237f6a/controller/controller.go:489 +0x349
```
